#%RAML 1.0
title: system api mulesoft to Ureg integeration
version: 1.0
mediaType: [ application/json ]
protocols: [ HTTP,HTTPS ]
traits:
  client-id-required: !include /api/Traits/client-id-enforcement.raml
  update: !include /api/Traits/put.raml 
resourceTypes:
  create-cust-Print: !include /api/ResourceTypes/create-customer-print.raml 
  create-cust-Digital: !include /api/ResourceTypes/create-customer-digital.raml
  update-cust-print: !include /api/ResourceTypes/update-customer-print.raml
  update-cust-Digital: !include /api/ResourceTypes/update-customer-digital.raml
  create-sub-print: !include /api/ResourceTypes/create-subscription-print.raml
  create-sub-digital: !include /api/ResourceTypes/create-subscription-digital.raml
  update-sub-complaints: !include /api/ResourceTypes/update-sub-complaints.raml
  update-sub-updates: !include /api/ResourceTypes/update-sub-updates.raml
  sync-customer-master: !include /api/ResourceTypes/sync-customer-master.raml
  unclaimed-digital-subscription: !include /api/ResourceTypes/unclaimed-digital-subscription.raml
  sync-sub: !include /api/ResourceTypes/sync-sub.raml
   
   
/customer:
  description: creates and updates print and digital customer 
  
  
  
  /createprint:
    description:  creating customer for  print 
    is : [ client-id-required ]
    type: create-cust-Print
  
  /createdigital:
    description: creating customer for digital
    is : [ client-id-required ]
    type: create-cust-Digital
  /updateprint:
    description: update customer for print
    type: update-cust-print 
    is : [ client-id-required,update ]

    
  /updatedigital:
    description: update customer for digital
    type: update-cust-Digital
    is : [ client-id-required,update ]
    

/subscription:
  description: creating print subscription and digital subscription
  
  /printSub:
    description: creates print subscription 
    type: create-sub-print
    is : [ client-id-required ]
  /digitalSub:
      description: creates digital subscription
      is : [ client-id-required ] 
      type : create-sub-digital

  /complaints:
    description: update subscription for complaints
    type: update-sub-complaints
    is : [ client-id-required,update ]
  /update:
    description: update subcription for updates
    type: update-sub-updates
    is : [ client-id-required ,update]

    
/sync:
  description: sync customer master 
  is: [client-id-required,update]
  type: sync-customer-master
/unclaimed:
  description: unclaimed digital subcription
  is: [client-id-required,update]
  type: unclaimed-digital-subscription
/syncsub:
  description: Sync subscription
  is: [client-id-required,update]
  type: sync-sub
    

  
