#%RAML 1.0 DataType
displayName: update subscription  
type: object
properties:
  user:
    type: string
    required: false
  appUserId:
    type: number
    required: true
  sapBpId:
    type: number
    required: false
  sfdcSubscriptionId:
    type: number
    required: true
  sapOrderId:
    type: number
    required: false
  posex:
    type: number
    required: false
  posnr:
    type: number
    required: false
  autoRenewal:
    type: boolean
    required: false
  startDate:
    type: string
    required: false
  endDate:
    type: string
    required: false
  orderType:
    type: string
    required: false
  publication:
    type: string
    required: false
  edition:
    type: string
    required: false
  serviceType:
    type: string
    required: false
  billingFrequency:
    type: string
    required: false
  orderStatus:
    type: string
    required: false

  

