#%RAML 1.0 Trait
queryParameters:
  client_id:
    description: Client id of the calling application
    required: true
    type: string
  client_secret:
    description: Client secret of the calling application
    required: true
    type: string